// Generated by https://quicktype.io

class InfectedHistory {
  List<History> items = new List();

  InfectedHistory();

  InfectedHistory.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    jsonList.forEach((item) {
      final infected = History.fromJsonMap(item);
      items.add(infected);
    });
  }
}

class History {
  String continent;
  int population;
  Cases cases;
  Deaths deaths;
  String day;
  String time;

  History({
    this.continent,
    this.population,
    this.cases,
    this.deaths,
    this.day,
    this.time,
  });

  History.fromJsonMap(Map<String, dynamic> json) {
    continent = json['continent'];
    population = json['population'];
    cases = Cases.fromJsonMap(json['cases']);
    deaths = Deaths.fromJsonMap(json['deaths']);
    day = json['day'];
    time = json['time'];
  }
}

class Cases {
  int active;
  int critical;
  int recovered;
  int total;

  Cases({
    this.active,
    this.critical,
    this.recovered,
    this.total,
  });

  Cases.fromJsonMap(Map<String, dynamic> json) {
    active = json['active'];
    critical = json['critical'];
    recovered = json['recovered'];
    total = json['total'];
  }
}

class Deaths {
  int total;

  Deaths({
    this.total,
  });

  Deaths.fromJsonMap(Map<String, dynamic> json) {
    total = json['total'];
  }
}
